api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token
from . import views


app_name = 'api'

urlpatterns = [
    path('', views.api_root),
    path('stories/', views.StoryList.as_view(), name='story-list'),
    path('stories/<uuid:pk>/', views.StoryDetail.as_view(), name='story-detail'),
    path('users/', views.UserList.as_view(), name='user-list'),
    path('users/<int:pk>/', views.UserDetail.as_view(), name='user-detail'),
    path('comments/', views.CommentList.as_view(), name='comment-list'),
    path('comments/<uuid:pk>/', views.CommentDetail.as_view(), name='comment-detail'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Custom Hackernews API documentation",
        default_version="v1",
        description="This documents the API with this project. It was generated by drf_yasg, a swagger-based schema "
                    "documenetation generation tool",
        contact=openapi.Contact(email="damiso15@yahoo.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls', namespace='news')),
    path("api/", include("api.urls")),
    path("api/docs", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from news import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('story-detail/<uuid:id>/<slug:slug>/', views.story_detail, name='story_detail'),
    path('paginate/', views.paginate, name='paginate'),
    path('search-by-text/', views.search_by_text, name='search_by_text'),
    path('filter-by-types/', views.search_by_text, name='filter_by_types')
]

templates/includes/_header.html
<!-- navbar -->
<div
  class="
    bg-white
    w-full
    fixed
    py-2
    px-2
    flex
    place-items-center
    justify-evenly
    space-x-2
    shadow
    z-10
  "
>
  <!-- logo -->
  <div class="flex text-3xl space-x-2 place-items-center">
    <a href="{% url 'news:index' %}">
      <span class="bg-white text-4xl" style="color: #ff5700">
        <i class="fab fa-hacker-news-square"></i>
      </span>
    </a>
    <p class="font-medium hidden lg:block">
      <a href="{% url 'news:index' %}">Hackernews</a>
    </p>
  </div>

  <!-- search bar -->
  <form
    id="searchForm"
    class="flex place-items-center bg-gray-100 rounded w-60 lg:w-80"
  >
    {% csrf_token %}
    <div class="pl-4 pr-2">
      <i class="fas fa-search"></i>
    </div>
    <input
      type="text"
      placeholder="Search for stories using title, author, text, and type of item"
      class="bg-gray-100 py-2 rounded outline-none w-full"
      id="storySearchBox"
    />
  </form>

  <div class="flex">
    <!-- coins -->
    <a
      class="
        flex
        place-items-center
        rounded-full
        border border-solid border-yellow-300
        md:px-4 md:py-2
        space-x-2
        bg-yellow-200
        hover:bg-yellow-500
      "
      href="https://github.com/damiso15"
    >
      <span
        class="
          rounded-full
          px-2
          bg-yellow-500
          border-2 border-solid border-white
          font-black
          text-white
          md:font-size-1
        "
      >
        &copy;
      </span>
      <span>SONAIKE Oluwadamilola.</span>
    </a>
  </div>
</div>